#!/bin/bash

coffee --output public/js/ --watch --compile coffee/*.coffee &
coffee --output public/js/models/ --watch --compile coffee/models/*.coffee &
coffee --output public/js/views/ --watch --compile coffee/views/*.coffee &
# coffee --output public/js/helpers/ --watch --compile coffee/helpers/*.coffee &
coffee --output public/js/routers/ --watch --compile coffee/routers/*.coffee &
coffee --output public/js/collections/ --watch --compile coffee/collections/*.coffee &
compass watch --sass-dir scss/ --css-dir public/css/ --output-style compressed --debug-info --trace &
./eco-compiler.js &
